# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Generate API code
      run: go generate ./...

    - name: Create UI stub
      run: mkdir -p ui/dist && echo '<!doctype html>' > ui/dist/index.html

    - name: Check module tidiness
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./internal/... ./pkg/...
